### ISSUE TITLE
Cannot convert object of type issue

### ISSUE THREAD

**Issue by linyang-ms** [MarkMpn/Sql4Cds#156]
[Write your comment/feedback/issue here]
Ever since the new version after 4.1.1, I'm not able to query with the tool on some of my entities because of the following error.
I'm not sure if it's something incorrectly configured on my entities. Please help to confirm. Thanks.
deploymentwave is a int type column, but I don't know how to specify int32 or int64.

Cannot convert object of type 'System.Data.SqlTypes.SqlInt64' to object of type 'System.Data.SqlTypes.SqlInt32'.Couldn't store <5> in deploymentwave Column.  Expected type is SqlInt32.
Cannot convert object of type 'System.Data.SqlTypes.SqlInt64' to object of type 'System.Data.SqlTypes.SqlInt32'.

---
- Deployment: Online
- DB Version: 9.2.21114.136
- Connection Controls Version: 1.2021.9.46
- XrmToolBox Version: 1.2021.12.53
- Tool Version: 5.4.1.0

**Comment by MarkMpn** [comment]
I can't see a `deploymentwave` column in my environment - what entity is this in?

It sounds similar to #152, where the metadata describes the column as being one type (integer in this case) but the virtual entity provider is actually returning values of another type (bigint/long/int64)

If this is the case then ideally either the metadata would need to be changed to set the type to BigInt, or the virtual entity provider would be changed to return int values rather than long values.

**Comment by linyang-ms** [comment]
Thanks, Mark.
It's a column in our customized entity.

In my code, it's defined as int type with IntegerAttributeMetadata as cds attribute metadata type.
In dataverse portal, it's displayed as Whole Number data type. I don't see an issue here.

To what you mentioned, where could I have a check on virtual entity provider?
<img width="247" alt="image" src="https://user-images.githubusercontent.com/88125911/150456766-9444db93-c38c-45ae-9350-bed75c6b4fc2.png">

**Comment by MarkMpn** [comment]
That attribute metadata is why SQL 4 CDS is expecting an Int32 value for this column, but for some reason it's receiving an Int64 value from the server. My guess is that this is because the data is coming from a virtual entity provider, or possibly a post-operation plugin.

You can get the list of virtual entities and their associated virtual entity provider using:

```sql
SELECT entity.logicalname,
       entitydataprovider.name
FROM   metadata.entity
       LEFT OUTER JOIN
       entitydataprovider
       ON entity.dataproviderid = entitydataprovider.entitydataproviderid
       LEFT OUTER JOIN
       entitydatasource
       ON entity.datasourceid = entitydatasource.entitydatasourceid
WHERE  entity.dataproviderid IS NOT NULL;
```

If your entity appears in this list I'd suggest you contact the developer of that data provider to ensure it will return Int32 values for this column.

It's also possible that the values are being changed by a plugin - you can find any plugins which could have an impact on this using:

```sql
SELECT plugintype.typename,
       sdkmessageprocessingstep.name,
       sdkmessagefilter.primaryobjecttypecode
FROM   sdkmessageprocessingstep
       INNER JOIN
       sdkmessagefilter
       ON sdkmessageprocessingstep.sdkmessagefilterid = sdkmessagefilter.sdkmessagefilterid
       INNER JOIN
       sdkmessage
       ON sdkmessagefilter.sdkmessageid = sdkmessage.sdkmessageid
       INNER JOIN
       plugintype
       ON sdkmessageprocessingstep.plugintypeid = plugintype.plugintypeid
WHERE  sdkmessagefilter.primaryobjecttypecode = 'cas_your_entity_name'
       AND sdkmessage.name = 'RetrieveMultiple'
       AND sdkmessageprocessingstep.mode = 0
       AND sdkmessageprocessingstep.stage >= 30;
```

**Comment by linyang-ms** [comment]
The entity is associated with a NonRelational Data Provider and the provider is returning a long type for this int type column.
I'm contacting with the developer and will update here if I got useful feedback.
Thanks for the clarification, Mark.

**Comment by linyang-ms** [comment]
Confirmed it's an issue happened in the data provider and going to be fixed.
Thanks for the help.
