### ISSUE TITLE
Use Sql4Cds in SSMS for SELECT also? (Goal = Export to SQL Server)

### ISSUE THREAD

**Issue by Liquidream** [MarkMpn/Sql4Cds#212]
Hi Mark,
Firstly, thanks for this great tool/library. 

I was wondering whether there is/could be an option for Sql4Cds to kick-in when also doing SELECT queries in SSMS?
As I'm still hitting the known 80MB query limit when trying to query large data in D365 (as below, with the plugin installed)
![image](https://user-images.githubusercontent.com/2211678/170685001-d6d151cc-7d9e-4727-8b82-ed527b6d3f19.png)

**My main end goal is actually to export our D365 data to an Azure SQL Database instance.**
However, we missed the boat on Data Export Service (now deprecated, can't be installed).

So, was hoping to use Sql4Cds in conjunction with SSMS to perform various exports to Azure SQL Database.
Even if we had to export table-by-table, that wouldn't be so bad.

Failing this, the only other thing I could think of was to use your .NET Engine and code something to 
(If you are aware of a better solution - I'd very much like to hear it)

Thanks in advance

**Comment by MarkMpn** [comment]
You can force it to use the SQL 4 CDS engine for SELECT statements if you include some option that the TDS Endpoint doesn't support. For example you could do:

```sql
SELECT * FROM activitypointer WHERE @@IDENTITY IS NULL
```

Assuming you haven't already run any `INSERT` commands in the same session, this would return all the activity records.

However, you could also investigate using the Synapse link to export your data to Azure Data Lake, then something like Azure Data Factory to load it into Azure SQL Database. Or use Synapse directly rather than using SQL Database at all if that's an option.
