### ISSUE TITLE
Request to add UPPER Function in SQL4CDS

### ISSUE THREAD

**Issue by sulimanbenhalim** [MarkMpn/Sql4Cds#283]
During a data quality exercise, I attempted to verify the accuracy of our data using my organization's local standard which specifies that family names should be capitalized. To achieve this, I utilized the following condition:

`WHERE (UNICODE(UPPER(tablename_familyname)) <> UNICODE(tablename_familyname))`

However, I found out that the SQL4CDS does not support the UPPER function.

Is there any other way to achieve this using SQL4CDS?

**Comment by MarkMpn** [comment]
Thanks, yes I should be able to add UPPER and LOWER support in a future update. However, your query would only check if the first character is upper case rather than the whole string, as UNICODE returns the code for the first character in the string. A better solution to check if the entire string is upper case would be to implement collation conversion so you can compare the strings case sensitively - this would be a bigger change but one I’ll investigate for this sort of situation.

**Comment by MarkMpn** [comment]
This is now included in v7.2
