### ISSUE TITLE
Attempting to DELTE 200K+ Rows Receiving Error Messages.

### ISSUE THREAD

**Issue by NathanHealea** [MarkMpn/Sql4Cds#299]
I'm trying to delete some audit logs from our institution Dataverse but when running the query in both MS SSMS and XRMToolBox I keep getting errors. 

```sql
DELETE 
FROM audit
WHERE 
    (month(audit.createdon) >= 1 AND month(audit.createdon) <= 12 )
    AND year(audit.createdon) = 2021
```

In MS SSMS using the SQ4CDS Package I get the following error.
![image](https://github.com/MarkMpn/Sql4Cds/assets/6578985/1cb55b3c-02e8-40df-b16f-fbb0da1e0ae7)
Even though it says that the operation was completed, they do when I verify if those audit logs still exist.

In XRMToolBox using SQL4CDS I get the following error.
`Hit maximum retrieval limit. This limit is in place to protect against excessive API requests. Try restricting the data to retrieve with WHERE clauses or eliminating subqueries.
Your limit of 100 retrievals per query can be modified in Settings.
`

I have tried to update my options to "Insert/Update/Delete records in batches of `1000`" and enabled `Use bulk delete operations` with no change in my results. 

![image](https://github.com/MarkMpn/Sql4Cds/assets/6578985/564d68cc-1d58-4158-b613-eb004b6369f1)

**Comment by MarkMpn** [comment]
The job will be listed in the `bulkdeleteoperation` table - you'll be able to see when it completes by monitoring the `statecode` field.

If you've still got the session open, run `SELECT @@IDENTITY` to get the ID of the bulk delete job. Otherwise you'll probably be able to find it with a `SELECT TOP 1 * FROM bulkdeleteoperation ORDER BY createdon DESC`
