### ISSUE TITLE
UpdateMultiple calls not honouring BYPASS_CUSTOM_PLUGIN_EXECUTION

### ISSUE THREAD

**Issue by SiPurdy** [MarkMpn/Sql4Cds#329]
This is with 7.3.0.0
Neither `OPTION (USE HINT ('BYPASS_CUSTOM_PLUGIN_EXECUTION'))` nor the Bypass custom plugins setting are taking affect, resulting in plugins running.

This was on an update of Contact, not sure if it's entity specific whether UpdateMultiple is used(with Bypass custom plugins is there any point in using UpdateMultiple????).

**Comment by MarkMpn** [comment]
Thanks, I'll get this fixed in the next update.

Not all entities currently support the new bulk operation methods so this will be entity specific.

Using the bulk messages allow some efficiencies within the server regardless of whether plugins are involved or not so SQL 4 CDS will use it when it's available even when you're bypassing plugins.

As a temporary workaround you can set the batch size to 1 which will force it to use a standard Update request instead.
