### ISSUE TITLE
Query failing in last two updates of SQL4CDS reporting "The given key was not present in the dictionary. See the Execution Plan tab for details of where this error occurred"

### ISSUE THREAD

**Issue by gpriestley** [MarkMpn/Sql4Cds#359]
A query that we run each day that normally takes under 5 minutes has been failing in the last two versions of SQL4CDS.
It successfully runs in XrmToolBox Version: 1.2023.2.64

The query is:

```sql
update contact
set pca_emailhardbounced=dateadd(hh,10,getdate())
-- select count(contactid) from contact
-- select contactid from contact
where donotbulkemail=0 and pca_emailhardbounced is null and emailaddress1 like '%@%.%'
and contactid in
(select distinct cdi_contactid from cdi_emailevent where cdi_type = 3 AND cdi_message NOT LIKE '%mailbox full%' AND cdi_message NOT LIKE '%hop count%' and createdon>=dateadd(day,-30,getdate()))
and contactid not in
(select distinct cdi_contactid from cdi_emailevent where cdi_type in (1,2,4) and createdon>=dateadd(day,-30,getdate()))
and contactid not in
(select distinct cdi_contactid from cdi_sentemail where cdi_senton>=dateadd(day,-30,getdate()) and (cdi_deliveriescount>0 or cdi_openscount>0 or cdi_clickscount>0))
```

If I run the query as is in the recent versions, it will take over 90 minutes before failing with:
"The given key was not present in the dictionary. See the Execution Plan tab for details of where this error occurred"

I've tried refactoring such as "group by" instead of "distinct" in the sub queries, and this runs quicker in around 5 minutes before failing with "The given key was not present in the dictionary"

Differences in estimated execution plans attached.

---
- Deployment: Online
- DB Version: 9.2.23084.182
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.9.66
- Tool Version: 7.5.2.0

## Not working

![Estimated execution plan - not working](https://github.com/MarkMpn/Sql4Cds/assets/90604235/d82534ea-df4b-4546-b1f3-cf26e1e0eec2)

## Working

![Estimated execution plan - works](https://github.com/MarkMpn/Sql4Cds/assets/90604235/25b43d45-2592-41d2-b8f1-ce535b807f33)

**Comment by gpriestley** [comment]
The file names of the graphic images aren't obvious - in case you can see the original name, the ones with Hash Joins are the ones that work, and the ones with the Merge Join and Sort aren't working.

**Comment by MarkMpn** [comment]
Thanks for the details, I’m working on a fix for this, hopefully it should be good to go next week. I’m trying to optimise the `NOT IN` and `NOT EXISTS` so hopefully this should run a lot faster as well.

**Comment by CREFaulk** [comment]
In the same timeframe a query I used to run now returns "Object reference not set to an instance of an object." instead of running. I've been using this query for months before then. The subquery still works but the entire statement won't execute anymore.

I created this example with standard CRM entities to reproduce the issue.

`select app.*
from (select l.leadid, c.originatingleadid, tot = sum(1)
from lead l with(nolock)
inner join contact c with(nolock) ON l.leadid = c.originatingleadid
where l.statecode = 0
group by l.leadid, c.originatingleadid
having sum(1) > 1) as dups
inner join lead app with(nolock) on app.leadid = dups.leadid
where app.statecode = 0
go`
