### ISSUE TITLE
request timeout

### ISSUE THREAD

**Issue by wiljohn2014** [MarkMpn/Sql4Cds#36]
The request channel timed out while waiting for a reply after 00:01:59.9989890. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.

**Comment by MarkMpn** [comment]
Can you give me a bit more context please? When do you get this error?

**Comment by malam-dev** [comment]
@MarkMpn I get this error too sometimes when doing some update (or even just select) statements that I guess takes too long. Running through the SQL TDS endpoint.

Example:
select
f.name
from new_datatable d
join account f on 
  replace(replace(replace(f.name,',',''),'LLC',''),'.','')
= replace(replace(replace(d.new_name,',',''),'LLC',''),'.','')

Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
The request channel timed out while waiting for a reply after 00:02:00. Increase the timeout value passed to the call to Request or increase the SendTimeout value on the Binding. The time allotted to this operation may have been a portion of a longer timeout.
RequestId: TDS;7a3a095a-7445-4ac5-ad4a-3239c6fce525;2
Time: 2021-02-25T20:18:39.9317747Z

**Comment by MarkMpn** [comment]
Yes, the TDS endpoint enforces a 2 minute timeout on queries. Out of interest, roughly how many records do you have in those tables?

As this error is originating from TDS endpoint there's nothing I can do about this in SQL 4 CDS.

Because your join is on calculated expressions there's no way for the underlying SQL Server to optimise this query so I'm not too surprised that this takes over 2 minutes to complete. If this is a query you want to run regularly you may be better off creating a new column to hold the standardised company name that you can use for the join directly.

**Comment by malam-dev** [comment]
@MarkMpn Roughly 250k and 50k records on the tables although it should only be accessing 10-20k because of addition where clauses I left out. 

Yes, I think adding standardized name fields will be the easiest and most robust solution for what I'm needing. Thanks for you the suggestion.
