### ISSUE TITLE
Issue trying to install SQL4CDS for Visusal Studio

### ISSUE THREAD

**Issue by emibanana** [MarkMpn/Sql4Cds#379]
Hi Mark, i am having trouble installing the SQL4CDS NuGet package, see below error message:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1101	Unable to find package XrmToolBox. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org, Package source	RestorialPMPlugin	D:\006_DataversePlugins\RestorialPMPlugin.csproj	1	

I have tried to install the XrmToolBoxPackage package but this doesnt work

Any help and tips?

![image](https://github.com/MarkMpn/Sql4Cds/assets/120373920/34fee22e-c0bc-4233-a810-80b4a5f63771)

**Comment by emibanana** [comment]
Also i dont have issue building my assembly, it seems just build and no issue, but instead of creating 1 .dll file, i now have a lot of .dll files in the publish folder, which none of them are able to register on Dataverse plugin registration tool.


![image](https://github.com/MarkMpn/Sql4Cds/assets/120373920/3bc4c8c9-697d-4250-ac0e-43320ff7e0a0)


More over, when i register my plugin on dataverse and re-produce trigger event, i got below exception in my plugin trace log:

System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: Could not load file or assembly 'MarkMpn.Sql4Cds.Engine, Version=7.6.1.0, Culture=neutral, PublicKeyToken=ca7add60645c016f' or one of its dependencies. The system cannot find the file specified. (Fault Detail is equal to Exception details: 
ErrorCode: 0x80040224
Message: Could not load file or assembly 'MarkMpn.Sql4Cds.Engine, Version=7.6.1.0, Culture=neutral, PublicKeyToken=ca7add60645c016f' or one of its dependencies. The system cannot find the file specified.
TimeStamp: 2023-10-27T15:47:02.5197196Z
OriginalException: PluginExecution
ExceptionSource: PluginExecution
--
).

but i dont see a way to add MarkMpn.Sql4Cds.Engine to my solution directly? 

So I am a bit loss, how can i make this SQL4CDS working in a dataverse plugin?

**Comment by MarkMpn** [comment]
The `MarkMpn.SQL4CDS` package is the XrmToolBox tool and isn't meant to be added to your project - it's only there because XrmToolBox uses NuGet for its own tool library. To use the `Sql4CdsConnection` and related classes you only need to install the `MarkMpn.Sql4Cds.Engine` package. You don't need the `MarkMpn.Sql4Cds.Engine.FetchXml` package.

Because your plugin will depend on these various additional assemblies you should use the [Dependent Assemblies](https://learn.microsoft.com/en-us/power-apps/developer/data-platform/dependent-assembly-plugins) feature to create a plugin package rather than a standalone plugin assembly.

**Comment by emibanana** [comment]
Thank you Mark! This is my first time writing this so sorry for lacking this knowledge.

I have seen to successfully pack the solution into a NuGet package:
![image](https://github.com/MarkMpn/Sql4Cds/assets/120373920/5ec4354e-326d-404c-ad7b-a58f98421b60)

I have removed my old assembly, registered the whole package, let the server cache clean itself by waiting a lone time, and it seems still giving me dependency error:

Exception Message: Could not load file or assembly 'MarkMpn.Sql4Cds.Engine, Version=7.6.1.0, Culture=neutral, PublicKeyToken=ca7add60645c016f' or one of its dependencies. The system cannot find the file specified.

ErrorCode: -2147220956
HexErrorCode: 0x80040224

Not sure what I did wrong? :(

**Comment by MarkMpn** [comment]
The package should include all the referenced assemblies - at the moment it's only including youre RestorialPMPlugin.dll assembly. Rather than listing MarkMpn.Sql4Cds.Engine as a dependency of the package it should include that dll and all the other referenced dlls in the same package. This should be done automatically by the build process if you use the Visual Studio template included in the Power Platform Tools or if you use the CLI to create your plugin project.

**Comment by emibanana** [comment]
> The package should include all the referenced assemblies - at the moment it's only including youre RestorialPMPlugin.dll assembly. Rather than listing MarkMpn.Sql4Cds.Engine as a dependency of the package it should include that dll and all the other referenced dlls in the same package. This should be done automatically by the build process if you use the Visual Studio template included in the Power Platform Tools or if you use the CLI to create your plugin project.

Issue resolved now! Thank you mark. but the detail is...I figured that server side plugin in no way can run code parrellelly and not breaking server sand box, so it's not actually suitable to execute daily traffic SQL enquiry. Looks like Power Automate with fetchXML is the only method that has the throughput capability :(
