### ISSUE TITLE
Extra filter conditions showing up in the fetchXML query

### ISSUE THREAD

**Issue by trobblob** [MarkMpn/Sql4Cds#530]
This morning, I noticed that some extra filter conditions were added to my query. I may be wrong, but it seems to me like this is an issue.

![image](https://github.com/user-attachments/assets/04e509ba-2689-4f2c-9273-0e3069d754e4)

**Comment by MarkMpn** [comment]
This is to keep it consistent with SQL semantics - in FetchXML, the `ne` operator will match a `null` value as being not equal to `SYSTEM`, but in SQL you would not expect this to match.

If you use the `DISTINCT FROM` operator instead of `<>` it will generate only the expected `ne` condition and not the additional `not-null` conditions.

**Comment by trobblob** [comment]
Thank you, sir!
