### ISSUE TITLE
After Bulk Delete Job Complete - Row count mismatch

### ISSUE THREAD

**Issue by ZohaibUddinKhan** [MarkMpn/Sql4Cds#55]
In one of the table/entity, there were 5.4 Million records. We created a Bulk delete job which deleted more or less 5.3 Million records. After Bulk Delete Job Finished, we wrote a query: 

SELECT count(*) FROM table/entity;

And, it is still giving us wrong row count as 5.4 Million records.

Thanks.

**Comment by MarkMpn** [comment]
This is likely due to some caching in the RetrieveTotalRecordCountRequest that's used for better performance in simple `SELECT count(*) FROM table` queries.

You can turn this off in the [settings](https://markcarrington.dev/sql-4-cds/#additional_settings) - can you try turning off this setting and trying again?

**Comment by ZohaibUddinKhan** [comment]
Works perfectly fine after turning off the 'Use RetrieveTotalRecordCount Request where possible'. Not an Issue.
