### ISSUE TITLE
Error installing (latest) version

### ISSUE THREAD

**Issue by RobinBronsteede** [MarkMpn/Sql4Cds#550]
When installing the update for SQL4CDS I get around 22 warnings and error pop-ups and the tool will not install and even break my XrmToolbox to start up. See image for message.
What is going on? Am I doing something wrong, do I miss any required dll's iin my windows or what....????...

![image](https://github.com/user-attachments/assets/9c8bc0fb-2da3-4289-8591-741611b00f89)

Help !!!

**Comment by MarkMpn** [comment]
This is an issue with the XrmToolBox plugin installer which will hopefully be fixed in the next release of that. In the meantime, after installing the new version please delete any files in the Plugins folder which also appear in the Plugins\MarkMpn.Sql4Cds folder – see some of the comments on https://markcarrington.dev/2024/07/12/sql-4-cds-v9-2-released/ for more information.

**Comment by RobinBronsteede** [comment]
Back on track, thanks for pointing in the right direction
