### ISSUE TITLE
Update without ReadAccess

### ISSUE THREAD

**Issue by clintonbale** [MarkMpn/Sql4Cds#567]
When trying to update the values of an entity that the executing user has WriteAccess but *not* ReadAccess to, no rows are updated:

```sql
UPDATE new_customentity
SET    new_test = 'Testing'
WHERE  new_customentityid = '...';
```

`(0 Custom Entities updated)`

The same query works fine on an administrative account, or if using `Update` manually with the Dataverse SDK and user impersonation.

Overall Access using the Access Checker on the record in PowerApps looks like the following:

![2024-10-15_15-12-13](https://github.com/user-attachments/assets/6c308546-45de-430a-9350-f12b99d16eb0)

---
- Deployment: Online
- DB Version: 9.2.24094.182
- Connection Controls Version: 1.2023.6.56
- XrmToolBox Version: 1.2023.12.68
- Tool Version: 9.3.0.0

**Comment by MarkMpn** [comment]
This will actually be the default behaviour in the next version with the fix for #248 - so long as you’re filtering on the primary key and are setting the fields to fixed values, it will no longer try to read the record before updating/deleting it. Look out for the next update, hopefully coming soon…
